export const GET_ALL_POSTS_SUCCESS = "GET_ALL_POSTS_SUCCESS";
export const GET_ALL_POSTS_FAILURE = "GET_ALL_POSTS_FAILURE";
export const GET_ALL_POSTS_REQUEST = "GET_ALL_POSTS_REQUEST";

export const GET_ONE_POST_SUCCESS = "GET_ONE_POST_SUCCESS";
export const GET_ONE_POST_FAILURE = "GET_ONE_POST_FAILURE";
export const GET_ONE_POST_REQUEST = "GET_ONE_POST_REQUEST";

export const LOAD_POSTS_BY_USER_ID_SUCCESS = "LOAD_POSTS_BY_USER_ID_SUCCESS";
export const LOAD_POSTS_BY_USER_ID_FAILURE = "LOAD_POSTS_BY_USER_ID_FAILURE";
export const LOAD_POSTS_BY_USER_ID_REQUEST = "LOAD_POSTS_BY_USER_ID_REQUEST";

export const CREATE_POST_SUCCESS = "CREATE_POST_SUCCESS";
export const CREATE_POST_FAILURE = "CREATE_POST_FAILURE";
export const CREATE_POST_REQUEST = "CREATE_POST_REQUEST";

export const ADD_COMMENT_TO_POST_SUCCESS = "ADD_COMMENT_TO_POST_SUCCESS";
export const ADD_COMMENT_TO_POST_FAILURE = "ADD_COMMENT_TO_POST_FAILURE";
export const ADD_COMMENT_TO_POST_REQUEST = "ADD_COMMENT_TO_POST_REQUEST";

export const ADD_UP_VOTE_TO_POST_SUCCESS = "ADD_UP_VOTE_TO_POST_SUCCESS";
export const ADD_UP_VOTE_TO_POST_FAILURE = "ADD_UP_VOTE_TO_POST_FAILURE";
export const ADD_UP_VOTE_TO_POST_REQUEST = "ADD_UP_VOTE_TO_POST_REQUEST";

export const ADD_DOWN_VOTE_TO_POST_SUCCESS = "ADD_DOWN_VOTE_TO_POST_SUCCESS";
export const ADD_DOWN_VOTE_TO_POST_FAILURE = "ADD_DOWN_VOTE_TO_POST_FAILURE";
export const ADD_DOWN_VOTE_TO_POST_REQUEST = "ADD_DOWN_VOTE_TO_POST_REQUEST";
